name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17 # මෙතැන 11 තිබුණු එක 17 කළා
        uses: actions/setup-java@v4
        with:
          java-version: '17' # මෙතැනත් 17 කළා
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: key-logger-apk
          path: app/build/outputs/apk/debug/*.apk
